### ISSUE TITLE
Move from `got` to `curl`

### ISSUE THREAD

**Issue by Kikobeats** [Kikobeats/html-get#22]
I need to investigate if could be possible move from `got` to `curl`

`curl` has better accuracy for getting HTML from securized websites.

That's the main library used by Insomnia Client:

https://github.com/getinsomnia/node-libcurl

**Example**

```js
var Curl = require('insomnia-node-libcurl').Curl

var curl = new Curl()

curl.setOpt('URL', 'www.google.com')
curl.setOpt('FOLLOWLOCATION', true)

curl.on('end', function (statusCode, body, headers) {
  console.info(statusCode)
  console.info('---')
  console.info(body.length)
  console.info('---')
  console.info(this.getInfo('TOTAL_TIME'))
  console.log(body)
  this.close()
})

curl.on('error', curl.close.bind(curl))
curl.perform()
```

My concern is that the API is a bit hard, need to create a good wrapper similar to `got` interface.

**Testing URLs**

- https://startse.com/noticia/netflix-do-esporte-planeja-chegada-ao-brasil-ma-noticia-para-globo

**Comment by gschier** [comment]
Just want to mention that, if you do end up adopting `libcurl`, you should use the main project here: https://github.com/JCMais/node-libcurl. The Insomnia fork is unstable and not meant for use from the general public
